# -*- coding: binary -*-
# frozen_string_literal: true
# Manually generated from MimeDetective nuget library
# Magic numbers sourced from wikipedia : https://en.wikipedia.org/wiki/List_of_file_signatures
# Mime types sourced from :
# * https://www.digipres.org/formats/mime-types/
# * https://rgfigueroa.files.wordpress.com/2008/05/mime-types1.pdf

class MimeMagic
  # @private
  # :nodoc:
  EXTENSIONS = {
    '3gp' => 'video/3gpp',
    '3gpp' => 'video/3gpp',
    '3g2' => 'video/3gpp2',
    '3gpp2' => 'video/3gpp2',
    '7z' => 'application/x-7z-compressed',
    '8sv' => 'application/iff',
    '8svx' => 'application/iff',
    'aac' => 'audio/aac',
    'aar' => 'application/zip',
    'acbm' => 'application/iff',
    'ace' => 'application/x-ace',
    'aff' => 'application/x-aff',
    'ai' => 'application/postscript',
    'aif' => 'audio/aiff',
    'aifc' => 'audio/aiff',
    'aiff' => 'audio/aiff',
    'alias' => 'application/x-alias',
    'anim' => 'application/iff',
    'apk' => 'application/vnd.android.package-archive',
    'arj' => 'application/public.archive.arj',
    'asf' => 'application/vnd.ms-asf',
    'avi' => 'video/avi',
    'avro' => 'avro/binary',
    'bac' => 'application/x-bac',
    'bin' => 'application/exe',
    'bmp' => 'image/bmp',
    'bpg' => 'image/x-bpg',
    'bz' => 'application/bzip2',
    'bz2' => 'application/bzip2',
    'cab' => 'application/vnd.ms-cab-compressed',
    'cda' => 'text/xml',
    'chm' => 'application/vnd.ms-htmlhelp',
    'cin' => 'application/x-cin',
    'cla' => 'application/x-java-class',
    'class' => 'application/x-java-class',
    'cls' => 'application/x-java-class',
    'cmus' => 'audio/aiff',
    'com' => 'application/exe',
    'cr2' => 'image/x-canon-cr2',
    'crx' => 'application/x-chrome-extension',
    'csv' => 'text/plain',
    'cwk' => 'application/x-appleworks',
    'daa' => 'application/x-daa',
    'dat' => 'application/octet-stream',
    'db' => 'application/vnd.sqlite3',
    'dba' => 'application/x-dba',
    'dcm' => 'image/dicom',
    'dcr' => 'application/x-director',
    'deb' => 'application/vnd.debian.binary-package',
    'der' => 'application/x-x509-ca-cert',
    'dex' => 'application/x-dalvik',
    'dib' => 'image/bmp',
    'dicm' => 'image/dicom',
    'dir' => 'application/x-director',
    'djv' => 'image/vnd.djvu',
    'djvu' => 'image/vnd.djvu',
    'dll' => 'application/exe',
    'dmg' => 'application/octet-stream',
    'doc' => 'application/msword',
    'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'dot' => 'application/msword',
    'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    'dpx' => 'image/x-dpx',
    'drc' => 'application/x-draco',
    'eml' => 'message/rfc822',
    'emlx' => 'message/rfc822',
    'epub' => 'application/epub+zip',
    'evt' => 'application/octet-stream',
    'exe' => 'application/exe',
    'exr' => 'image/x-exr',
    'ez2' => 'application/vnd.ezpix-album',
    'ez3' => 'application/vnd.ezpix-package',
    'fh8' => 'image/x-freehand',
    'fla' => 'audio/flac',
    'flac' => 'audio/flac',
    'flif' => 'image/flif',
    'flv' => 'video/x-flv',
    'gif' => 'image/gif',
    'gz' => 'application/x-gzip',
    'htm' => 'text/html',
    'html' => 'text/html',
    'ibm' => 'application/iff',
    'ical' => 'text/calendar',
    'ico' => 'image/x-icon',
    'ics' => 'text/calendar',
    'iff' => 'application/iff',
    'ilbm' => 'application/iff',
    'iso' => 'application/octet-stream',
    'isz' => 'application/octet-stream',
    'jar' => 'application/java-archive',
    'java' => 'text/x-java',
    'jpeg' => 'image/jpeg',
    'jpg' => 'image/jpeg',
    'kmz' => 'application/vnd.google-earth.kmz',
    'lbm' => 'application/iff',
    'luac' => 'application/x-lua-bytecode',
    'lz' => 'application/lzip',
    'm1a' => 'video/mpeg',
    'm1v' => 'video/mpeg',
    'm2a' => 'video/mpeg',
    'm2p' => 'video/mpeg',
    'm2t' => 'video/mp2t',
    'm4v' => 'video/x-m4v',
    'maff' => 'application/x-maff',
    'mbx' => 'message/rfc822',
    'mid' => 'audio/midi',
    'midi' => 'audio/midi',
    'mk3d' => 'video/x-matroska',
    'mka' => 'video/x-matroska',
    'mks' => 'video/x-matroska',
    'mkv' => 'video/x-matroska',
    'mov' => 'video/quicktime',
    'mp1' => 'audio/mpeg',
    'mp2' => 'audio/mpeg',
    'mp3' => 'audio/mp3',
    'mp4' => 'video/mp4',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'msg' => 'message/rfc822',
    'mus' => 'audio/aiff',
    'nes' => 'application/octet-stream',
    'odex' => 'application/x-dalvik',
    'odp' => 'application/vnd.oasis.opendocument.presentation',
    'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
    'odt' => 'application/vnd.oasis.opendocument.text',
    'oga' => 'audio/ogg',
    'ogg' => 'audio/ogg',
    'ogv' => 'video/ogg',
    'orc' => 'application/x-orc',
    'ost' => 'application/vnd.ms-outlook',
    'pab' => 'application/vnd.ms-outlook',
    'pbm' => 'image/x-portable-anymap',
    'pcap' => 'application/vnd.tcpdump.pcap',
    'pdf' => 'application/pdf',
    'pgm' => 'image/x-portable-anymap',
    'pgp' => 'application/pgp',
    'pk3' => 'application/x-compressed',
    'pk4' => 'application/x-compressed',
    'pm' => 'image/x-xbitmap',
    'png' => 'image/png',
    'pnm' => 'image/x-portable-anymap',
    'pot' => 'application/vnd.ms-powerpoint',
    'potx' => 'application/vnd.openxmlformats-officedocument.presentationml.template',
    'ppm' => 'image/x-portable-anymap',
    'pps' => 'application/vnd.ms-powerpoint',
    'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'ppt' => 'application/vnd.ms-powerpoint',
    'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'ps' => 'application/postscript',
    'psd' => 'application/x-photoshop',
    'pst' => 'application/vnd.ms-outlook',
    'qcp' => 'application/x-rtsp',
    'qt' => 'video/quicktime',
    'rar' => 'application/vnd.rar',
    'rb' => 'application/x-ruby',
    'rm' => 'video/realmedia',
    'rpm' => 'application/x-redhat-package-manager',
    'rtf' => 'application/x-rtf',
    'sh' => 'application/x-sh',
    'sml' => 'application/x-jackson-smile',
    'smu' => 'application/iff',
    'smus' => 'application/iff',
    'snd' => 'application/iff',
    'sqlite' => 'application/vnd.sqlite3',
    'sqlitedb' => 'application/vnd.sqlite3',
    'svg' => 'image/svg+xml',
    'svx' => 'application/iff',
    'swf' => 'application/x-shockwave-flash',
    'sxc' => 'application/vnd.sun.xml.calc',
    'sxd' => 'application/vnd.sun.xml.draw',
    'sxi' => 'application/vnd.sun.xml.impress',
    'sxw' => 'application/vnd.sun.xml.writer',
    'tar' => 'application/x-tar',
    'tar.gz' => 'application/x-gzip',
    'tbv2' => 'application/bzip2',
    'tdef' => 'application/x-telegram',
    'tdf$' => 'application/x-telegram',
    'tif' => 'image/tiff',
    'tiff' => 'image/tiff',
    'tox' => 'application/x-tox',
    'ts' => 'video/mp2t',
    'tsa' => 'video/mp2t',
    'tsv' => 'video/mp2t',
    'txt' => 'text/plain',
    'usdz' => 'model/vnd.usdz+zip',
    'vdi' => 'application/octet-stream',
    'vhd' => 'application/octet-stream',
    'vhdx' => 'application/octet-stream',
    'vmdk' => 'application/x-vmdk',
    'vob' => 'video/mpeg',
    'vsdx' => 'application/vnd.visio2013',
    'wasm' => 'application/wasm',
    'wav' => 'audio/wav',
    'webm' => 'video/x-matroska',
    'webp' => 'image/webp',
    'wma' => 'audio/x-ms-wma',
    'wmf' => 'image/wmf',
    'wmv' => 'video/x-ms-wmv',
    'woff' => 'font/woff',
    'woff2' => 'font/woff2',
    'wpd' => 'application/vnd.wordperfect',
    'xar' => 'application/x-xar',
    'xcf' => 'image/xcf',
    'xls' => 'application/excel',
    'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xlt' => 'application/vnd.ms-excel',
    'xltx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    'xml' => 'text/xml',
    'xpi' => 'application/x-xpinstall',
    'xpm' => 'image/x-xbitmap',
    'yuv' => 'application/iff',
    'yuvn' => 'application/iff',
    'zip' => 'application/zip',
    'zlib' => 'application/zlib',
    'zoo' => 'application/x-zoo',
    'zst' => 'application/zstd',
  }
  # @private
  # :nodoc:

  TYPES = {
    'application/octet-stream'                                                  => [EXTENSIONS.keys, %w(), 'Octet stream'],
    'application/vnd.ms-excel'                                                  => [%w(xls csv xlt), %w(), 'XLS'],
    'application/excel'                                                         => [%w(xls csv xlt), %w(), 'XLS'],
    'image/gif'                                                                 => [%w(gif), %w(), 'GIF'],
    'image/jpeg'                                                                => [%w(jpg jpeg), %w(), 'JPG'],
    'image/png'                                                                 => [%w(png), %w(), 'PNG'],
    'image/vnd.adobe.photoshop'                                                 => [%w(psd), %w(), 'PSD'],
    'application/x-photoshop'                                                   => [%w(psd), %w(), 'PSD'],
    'application/photoshop'                                                     => [%w(psd), %w(), 'PSD'],
    'application/psd'                                                           => [%w(psd), %w(), 'PSD'],
    'image/psd'                                                                 => [%w(psd), %w(), 'PSD'],
    'image/svg+xml'                                                             => [%w(svg), %w(), 'SVG'],
    'text/plain'                                                                => [%w(svg csv txt htm html), %w(), 'Text'],
    'text/html'                                                                 => [%w(htm html), %w(text/plain), 'HTML document'],
    'application/xhtml+xml'                                                     => [%w(htm html), %w(text/plain), 'HTML document'],
    'text/xml'                                                                  => [%w(xml cda), %w(text/plain), "XML"],
    'application/xml'                                                           => [%w(xml), %w(text/xml), "XML"],
    'application/vnd.sun.xml.draw'                                              => [%w(sxd), %w(application/zip), 'SXD'],
    'application/zip'                                                           => [%w(
                                                                                        zip sxd odp potx ppsx pptx sxi ods sxc xltx xlsx dotx odt
                                                                                        docx sxw aar
                                                                                    ), %w(), 'ZIP'],
    'application/x-compressed'                                                  => [%w(
                                                                                        sxd odp potx ppsx pptx sxi ods sxc xltx xlsx dotx odt docx
                                                                                        sxw 7z rar pk3 pk4
                                                                                    ), %w(), 'Compressed file'],
    'image/tiff'                                                                => [%w(tif tiff), %w(), 'Tiff'],
    'image/bmp'                                                                 => [%w(bmp dib), %w(), 'BMP'],
    'audio/aac'                                                                 => [%w(aac), %w(), 'AAC'],
    'audio/vnd.dlna.adts'                                                       => [%w(aac), %w(), 'AAC'],
    'audio/wav'                                                                 => [%w(wav), %w(), 'WAV'],
    'application/vnd.oasis.opendocument.presentation'                           => [%w(odp), %w(application/zip), 'ODP'],
    'application/vnd.ms-powerpoint'                                             => [%w(pot pps ppt), %w(), 'POT'],
    'application/vnd.openxmlformats-officedocument.presentationml.template'     => [%w(potx), %w(application/zip), 'POTX'],
    'application/vnd.openxmlformats-officedocument.presentationml.slideshow'    => [%w(ppsx), %w(application/zip), 'PPSX'],
    'application/vnd.openxmlformats-officedocument.presentationml.presentation' => [%w(pptx), %w(application/zip), 'PPTX'],
    'application/vnd.sun.xml.impress'                                           => [%w(sxi), %w(application/zip), 'SXI'],
    'application/vnd.oasis.opendocument.spreadsheet'                            => [%w(ods), %w(application/zip), 'ODS'],
    'application/vnd.sun.xml.calc'                                              => [%w(sxc), %w(application/zip), 'SXC'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.template'      => [%w(xltx), %w(application/zip), 'XLTX'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'         => [%w(xlsx), %w(application/zip), 'XLSX'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.template'   => [%w(dotx), %w(application/zip), 'DOTX'],
    'application/x-tar'                                                         => [%w(tar), %w(), 'TAR'],
    'application/x-ruby'                                                        => [%w(rb), %w(), 'Ruby'],
    'application/vnd.oasis.opendocument.text'                                   => [%w(odt), %w(application/zip), 'ODT'],
    'application/msword'                                                        => [%w(doc msg rtf dot), %w(), 'DOC'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'   => [%w(docx), %w(application/zip), 'DOCX'],
    'message/rfc822'                                                            => [%w(eml emlx mbx msg), %w(), 'EML'],
    'text-calendar'                                                             => [%w(ical ics), %w(), 'ICAL'],
    'application/vnd.sun.xml.writer'                                            => [%w(sxw), %w(application/zip), 'SXW'],
    'application/vnd.wordperfect'                                               => [%w(wpd), %w(), 'WPD'],
    'video/mpeg'                                                                => [%w(m1a m1v m2a mpeg mpg m2p vob), %w(), 'MPEG'],
    'video/x-m4v'                                                               => [%w(m4v), %w(), 'M4V'],
    'video/quicktime'                                                           => [%w(mov qt), %w(), 'Quicktime'],
    'audio/mpeg'                                                                => [%w(mp1 mp2 mp3), %w(), 'MPEG Audio'],
    'audio/mp3'                                                                 => [%w(mp3), %w(), 'MP3'],
    'video/realmedia'                                                           => [%w(rm), %w(), 'Realmedia'],
    'video/x-matroska'                                                          => [%w(webm mkv mk3d mka mks), %w(), 'Webmedia'],
    'video/x-ms-wmv'                                                            => [%w(wmv), %w(), 'Windows Media Video'],
    'video/mp4'                                                                 => [%w(mp4), %w(), 'MP4'],
    'video/avi'                                                                 => [%w(avi), %w(), 'AVI'],
    'application/pdf'                                                           => [%w(pdf), %w(), 'PDF'],
    'application/x-rtf'                                                         => [%w(rtf), %w(), 'RTF'],
    'application/rtf'                                                           => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/rtf'                                                                  => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/richtext'                                                             => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'application/doc'                                                           => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'application/x-soffice'                                                     => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/x-java'                                                               => [%w(java), %w(text/plain), "Java"],
    'text/java'                                                                 => [%w(java), %w(text/plain), "Java"],
    'text/x-java-source'                                                        => [%w(java), %w(text/plain), "Java"],
    'application/ms-java'                                                       => [%w(java), %w(text/plain), "Java"],
    'application/x-7z-compressed'                                               => [%w(7z), %w(), "7zip"],
    'application/vnd.rar'                                                       => [%w(rar), %w(), "Rar"],
    'application/vnd.ms-outlook'                                                => [%w(pab pst ost), %w(), 'PST'],
    'video/3gpp'                                                                => [%w(3gp 3gpp), %w(), '3gp'],
    'video/3gpp2'                                                               => [%w(3g2 3gpp2), %w(), '3g2'],
    'application/iff'                                                           => [%w(
                                                                                        8sv 8svx acbm anim ibm iff ilbm lbm smu smus snd svx yuv
                                                                                        yuvn
                                                                                    ), %w(), '8sv'],
    'application/x-ace'                                                         => [%w(ace), %w(), 'ace'],
    'application/x-aff'                                                         => [%w(aff), %w(), 'aff'],
    'application/postscript'                                                    => [%w(ai ps), %w(), 'ai'],
    'audio/aiff'                                                                => [%w(aif aifc aiff cmus mus), %w(), 'aif'],
    'application/x-alias'                                                       => [%w(alias), %w(), 'alias'],
    'application/vnd.android.package-archive'                                   => [%w(apk), %w(), 'apk'],
    'application/public.archive.arj'                                            => [%w(arj), %w(), 'arj'],
    'application/vnd.ms-asf'                                                    => [%w(asf), %w(), 'asf'],
    'avro/binary'                                                               => [%w(avro), %w(), 'avro'],
    'application/x-bac'                                                         => [%w(bac), %w(), 'bac'],
    'application/exe'                                                           => [%w(bin com exe dll), %w(), 'bin'],
    'image/x-bpg'                                                               => [%w(bpg), %w(), 'bpg'],
    'application/bzip2'                                                         => [%w(bz bz2 tbv2), %w(), 'bzip'],
    'application/vnd.ms-cab-compressed'                                         => [%w(cab), %w(), 'cab'],
    'application/vnd.ms-htmlhelp'                                               => [%w(chm), %w(), 'chm'],
    'application/x-cin'                                                         => [%w(cin), %w(), 'cin'],
    'application/x-java-class'                                                  => [%w(cla class cls), %w(), 'cla'],
    'image/x-canon-cr2'                                                         => [%w(cr2), %w(), 'cr2'],
    'application/x-chrome-extension'                                            => [%w(crx), %w(), 'crx'],
    'application/x-appleworks'                                                  => [%w(cwk), %w(), 'cwk'],
    'application/x-daa'                                                         => [%w(daa), %w(), 'daa'],
    'application/vnd.sqlite3'                                                   => [%w(db sqlite sqlitedb), %w(), 'db'],
    'application/x-dba'                                                         => [%w(dba), %w(), 'dba'],
    'image/dicom'                                                               => [%w(dcm dicm), %w(), 'dcm'],
    'application/x-director'                                                    => [%w(dcr dir), %w(), 'dcr'],
    'application/vnd.debian.binary-package'                                     => [%w(deb), %w(), 'deb'],
    'application/x-x509-ca-cert'                                                => [%w(der), %w(), 'der'],
    'application/x-dalvik'                                                      => [%w(dex odex), %w(), 'dex'],
    'image/vnd.djvu'                                                            => [%w(djv djvu), %w(), 'djv'],
    'image/x-dpx'                                                               => [%w(dpx), %w(), 'dpx'],
    'application/x-draco'                                                       => [%w(drc), %w(), 'drc'],
    'application/epub+zip'                                                      => [%w(epub), %w(), 'epub'],
    'image/x-exr'                                                               => [%w(exr), %w(), 'exr'],
    'application/vnd.ezpix-album'                                               => [%w(ez2), %w(), 'ez2'],
    'application/vnd.ezpix-package'                                             => [%w(ez3), %w(), 'ez3'],
    'image/x-freehand'                                                          => [%w(fh8), %w(), 'fh8'],
    'audio/flac'                                                                => [%w(fla flac), %w(), 'fla'],
    'image/flif'                                                                => [%w(flif), %w(), 'flif'],
    'video/x-flv'                                                               => [%w(flv), %w(), 'flv'],
    'application/x-gzip'                                                        => [%w(gz tar.gz), %w(), 'gz'],
    'text/calendar'                                                             => [%w(ical ics), %w(), 'ical'],
    'image/x-icon'                                                              => [%w(ico), %w(), 'ico'],
    'application/java-archive'                                                  => [%w(jar), %w(), 'jar'],
    'application/vnd.google-earth.kmz'                                          => [%w(kmz), %w(), 'kmz'],
    'application/x-lua-bytecode'                                                => [%w(luac), %w(), 'luac'],
    'application/lzip'                                                          => [%w(lz), %w(), 'lz'],
    'video/mp2t'                                                                => [%w(m2t ts tsa tsv), %w(), 'm2t'],
    'application/x-maff'                                                        => [%w(maff), %w(), 'maff'],
    'audio/midi'                                                                => [%w(mid midi), %w(), 'mid'],
    'audio/ogg'                                                                 => [%w(oga ogg), %w(), 'oga'],
    'video/ogg'                                                                 => [%w(ogv), %w(), 'ogv'],
    'application/x-orc'                                                         => [%w(orc), %w(), 'orc'],
    'image/x-portable-anymap'                                                   => [%w(pbm pgm pnm ppm), %w(), 'pbm'],
    'application/vnd.tcpdump.pcap'                                              => [%w(pcap), %w(), 'pcap'],
    'application/pgp'                                                           => [%w(pgp), %w(), 'pgp'],
    'image/x-xbitmap'                                                           => [%w(pm xpm), %w(), 'pm'],
    'application/x-rtsp'                                                        => [%w(qcp), %w(), 'qcp'],
    'application/x-redhat-package-manager'                                      => [%w(rpm), %w(), 'rpm'],
    'application/x-sh'                                                          => [%w(sh), %w(), 'sh'],
    'application/x-jackson-smile'                                               => [%w(sml), %w(), 'sml'],
    'application/x-shockwave-flash'                                             => [%w(swf), %w(), 'swf'],
    'application/x-telegram'                                                    => [%w(tdef tdf$), %w(), 'tdef'],
    'application/x-tox'                                                         => [%w(tox), %w(), 'tox'],
    'model/vnd.usdz+zip'                                                        => [%w(usdz), %w(), 'usdz'],
    'application/x-vmdk'                                                        => [%w(vmdk), %w(), 'vmdk'],
    'application/vnd.visio2013'                                                 => [%w(vsdx), %w(), 'vsdx'],
    'application/wasm'                                                          => [%w(wasm), %w(), 'wasm'],
    'image/webp'                                                                => [%w(webp), %w(), 'webp'],
    'audio/x-ms-wma'                                                            => [%w(wma), %w(), 'wma'],
    'image/wmf'                                                                 => [%w(wmf), %w(), 'wmf'],
    'font/woff'                                                                 => [%w(woff), %w(), 'woff'],
    'font/woff2'                                                                => [%w(woff2), %w(), 'woff2'],
    'application/x-xar'                                                         => [%w(xar), %w(), 'xar'],
    'image/xcf'                                                                 => [%w(xcf), %w(), 'xcf'],
    'application/x-xpinstall'                                                   => [%w(xpi), %w(), 'xpi'],
    'application/zlib'                                                          => [%w(zlib), %w(), 'zlib'],
    'application/x-zoo'                                                         => [%w(zoo), %w(), 'zoo'],
    'application/zstd'                                                          => [%w(zst), %w(), 'zst'],
  }

  #EXTENSIONS.each do |key, value|
  #  if not TYPES.keys.include?(value)
  #      puts "'" + value + "' => [%w(" + key + "), %w(), '" + key + "'],"
  #  else
  #      if not TYPES[value][0].include?(key)
  #          puts "Add " + key + " to " + value
  #      end
  #  end
  #end

  # @private
  # :nodoc:
  MAGIC = [
    ['application/zip',                             [[0, "\x50\x4B\x03\x04"]]],
    ['application/msword',                          [[0, "\xEC\xA5\xC1\x00"]]],
    ['application/excel',                           [[0, "\x09\x08\x10\x00\x00\x06\x05\x00"]]],
    ['application/mspowerpoint',                    [[0, "\xFD\xFF\xFF\xFF", [5, "\x00\x00\x00"]]]],
    ['application/rtf',                             [[0, "\x7B\x5C\x72\x74\x66\x31"]]],
    ['application/pdf',                             [[0, "\x25\x50\x44\x46"]]],
    ['text/xml',                                    [[0, "\x72\x73\x69\x6F\x6E\x3D\x22\x31\x2E\x30\x22\x3F\x3E"]]],
    ['text/plain',                                  [[0, "\xEF\xBB\xBF"]]],
    ['text/plain',                                  [[0, "\xFE\xFF"]]],
    ['text/plain',                                  [[0, "\xFF\xFE"]]],
    ['text/plain',                                  [[0, "\x00\x00\xFE\xFF"]]],
    ['text/plain',                                  [[0, "\xFF\xFE\x00\x00"]]],
    ['image/jpeg',                                  [[0, "\xFF\xD8\xFF"]]],
    ['image/png',                                   [[0, "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A"]]],
    ['image/gif',                                   [[0, "\x47\x49\x46\x38", [5, "\x61"]]]],
    ['image/bmp',                                   [[0, "\x66\x77"]]],
    ['image/x-icon',                                [[0, "\x00\x00\x01\x00"]]],
    ['application/gzip',                            [[0, "\x1F\x8B\x08"]]],
    ['application/x-7z-compressed',                 [[0, "\x66\x77"]]],
    ['application/x-7z-compressed',                 [[0, "\x37\x7A\xBC\xAF\x27\x1C"]]],
    ['application/vnd.rar',                         [[0, "\x52\x61\x72\x21"]]],
    ['application/octet-stream',                    [[0, "\x4D\x5A"]]],
    ['application/x-tar',                           [[0, "\x1F\x9D"]]],
    ['application/x-tar',                           [[0, "\x1F\xA0"]]],
    ['application/x-tar',                           [[257, "\x75\x73\x74\x61\x72\x00\x30\x30"]]],
    ['application/x-tar',                           [[257, "\x75\x73\x74\x61\x72\x20\x20\x00"]]],
    ['application/x-bzip',                          [[0, "\x42\x5A\x68"]]],
    ['application/ogg',                             [[0, "\x67\x67\x83\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00"]]],
    ['audio/midi',                                  [[0, "\x4D\x54\x68\x64"]]],
    ['audio/wav',                                   [[0, "\x52\x49\x46\x46", [8, "\x57\x41\x56\x45\x66\x6D\x74\x20"]]]],
    ['application/vnd.ms-outlook',                  [[0, "\x21\x42\x44\x4E"]]],
    ['application/acad',                            [[0, "\x41\x43\x31\x30"]]],
    ['application/x-photoshop',                     [[0, "\x38\x42\x50\x53"]]],
    ['message/rfc822',                              [[0, "\x46\x72\x6F\x6D"]]],
    ['text/plain',                                  [[0, ""]]],
  ]
end

#word
