# -*- coding: binary -*-
# frozen_string_literal: true
# Manually generated from MimeDetective nuget library
class MimeMagic
  # @private
  # :nodoc:
  EXTENSIONS = {
    'xls' => 'application/excel',
    'gif' => 'image/gif',
    'jpg' => 'image/jpeg',
    'jpeg' => 'image/jpeg',
    'png' => 'image/png',
    'psd' => 'application/x-photoshop',
    'svg' => 'image/svg+xml',
    'sxd' => 'application/vnd.sun.xml.draw',
    'tif' => 'image/tiff',
    'tiff' => 'image/tiff',
    'bmp' => 'image/bmp',
    'aac' => 'audio/aac',
    'wav' => 'audio/wav',
    'odp' => 'application/vnd.oasis.opendocument.presentation',
    'pot' => 'application/vnd.ms-powerpoint',
    'potx' => 'application/vnd.openxmlformats-officedocument.presentationml.template',
    'pps' => 'application/vnd.ms-powerpoint',
    'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'ppt' => 'application/vnd.ms-powerpoint',
    'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'sxi' => 'application/vnd.sun.xml.impress',
    'csv' => 'text/plain',
    'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
    'sxc' => 'application/vnd.sun.xml.calc',
    'xlt' => 'application/vnd.ms-excel',
    'xltx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'dot' => 'application/msword',
    'txt' => 'text/plain',
    'htm' => 'text/html',
    'html' => 'text/html',
    'zip' => 'application/zip',
    'tar' => 'application/x-tar',
    'rb' => 'application/x-ruby',
    'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    'odt' => 'application/vnd.oasis.opendocument.text',
    'doc' => 'application/msword',
    'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'eml' => 'message/rfc822',
    'emlx' => 'message/rfc822',
    'ical' => 'text/calendar',
    'ics' => 'text/calendar',
    'mbx' => 'message/rfc822',
    'msg' => 'message/rfc822',
    'sxw' => 'application/vnd.sun.xml.writer',
    'wpd' => 'application/vnd.wordperfect',
    'm1a' => 'video/mpeg',
    'm1v' => 'video/mpeg',
    'm2a' => 'video/mpeg',
    'm4v' => 'video/x-m4v',
    'mov' => 'video/quicktime',
    'mp1' => 'audio/mpeg',
    'mp2' => 'audio/mpeg',
    'mp3' => 'audio/mp3',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'qt' => 'video/quicktime',
    'rm' => 'video/realmedia',
    'webm' => 'video/x-matroska',
    'wmv' => 'video/x-ms-wmv',
    'mp4' => 'video/mp4',
    'mkv' => 'video/x-matroska',
    'avi' => 'video/avi',
    'pdf' => 'application/pdf',
    'rtf' => 'application/x-rtf',
    'xml' => 'application/xml',
    'java' => 'text/x-java',
    '7z' => 'application/x-7z-compressed',
    'rar' => 'application/vnd.rar',
    'pab' => 'application/vnd.ms-outlook',
    'pst' => 'application/vnd.ms-outlook',
    'ost' => 'application/vnd.ms-outlook',
  }
  # @private
  # :nodoc:
  TYPES = {
    'application/octet-stream'                                                  => [%w(
                                                                                        xls xlt xltx xlsx gif jpg jpeg png psd svg sxd tif tiff bmp
                                                                                        aac wav odp pot potx pps ppsx ppt pptx sxi csv ods sxc dot
                                                                                        dotx odt doc eml emlx ical ics mbx msg sxw wpd m1a m1v m2a
                                                                                        m4v mov mp1 mp2 mp3 mpeg mpg qt rm webm wmv mp4 mkv avi pdf
                                                                                        txt rtf xml java 7z rar pab pst ost
                                                                                    ), %w(), 'Octet stream'],
    'application/vnd.ms-excel'                                                  => [%w(xls csv xlt), %w(), 'XLS'],
    'application/excel'                                                         => [%w(xls csv xlt), %w(), 'XLS'],
    'image/gif'                                                                 => [%w(gif), %w(), 'GIF'],
    'image/jpeg'                                                                => [%w(jpg jpeg), %w(), 'JPG'],
    'image/png'                                                                 => [%w(png), %w(), 'PNG'],
    'image/vnd.adobe.photoshop'                                                 => [%w(psd), %w(), 'PSD'],
    'application/x-photoshop'                                                   => [%w(psd), %w(), 'PSD'],
    'application/photoshop'                                                     => [%w(psd), %w(), 'PSD'],
    'application/psd'                                                           => [%w(psd), %w(), 'PSD'],
    'image/psd'                                                                 => [%w(psd), %w(), 'PSD'],
    'image/svg+xml'                                                             => [%w(svg xml), %w(), 'SVG'],
    'text/plain'                                                                => [%w(svg csv txt htm html), %w(), 'Text'],
    'text/html'                                                                 => [%w(htm html), %w(text/plain), 'HTML document'],
    'application/xhtml+xml'                                                     => [%w(htm html), %w(text/plain), 'HTML document'],
    'application/xml'                                                           => [%w(xml), %w(text/plain), "XML"],
    'application/vnd.sun.xml.draw'                                              => [%w(sxd), %w(application/zip), 'SXD'],
    'application/zip'                                                           => [%w(
                                                                                        zip sxd odp potx ppsx pptx sxi ods sxc xltx xlsx dotx odt
                                                                                        docx sxw
                                                                                    ), %w(), 'ZIP'],
    'application/x-compressed'                                                  => [%w(
                                                                                        sxd odp potx ppsx pptx sxi ods sxc xltx xlsx dotx odt docx
                                                                                        sxw 7z rar
                                                                                    ), %w(), 'Compressed file'],
    'image/tiff'                                                                => [%w(tif tiff), %w(), 'Tiff'],
    'image/bmp'                                                                 => [%w(bmp), %w(), 'BMP'],
    'audio/aac'                                                                 => [%w(aac), %w(), 'AAC'],
    'audio/vnd.dlna.adts'                                                       => [%w(aac), %w(), 'AAC'],
    'audio/wav'                                                                 => [%w(wav), %w(), 'WAV'],
    'application/vnd.oasis.opendocument.presentation'                           => [%w(odp), %w(application/zip), 'ODP'],
    'application/vnd.ms-powerpoint'                                             => [%w(pot pps ppt), %w(), 'POT'],
    'application/vnd.openxmlformats-officedocument.presentationml.template'     => [%w(potx), %w(application/zip), 'POTX'],
    'application/vnd.openxmlformats-officedocument.presentationml.slideshow'    => [%w(ppsx), %w(application/zip), 'PPSX'],
    'application/vnd.openxmlformats-officedocument.presentationml.presentation' => [%w(pptx), %w(application/zip), 'PPTX'],
    'application/vnd.sun.xml.impress'                                           => [%w(sxi), %w(application/zip), 'SXI'],
    'application/vnd.oasis.opendocument.spreadsheet'                            => [%w(ods), %w(application/zip), 'ODS'],
    'application/vnd.sun.xml.calc'                                              => [%w(sxc), %w(application/zip), 'SXC'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.template'      => [%w(xltx), %w(application/zip), 'XLTX'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'         => [%w(xlsx), %w(application/zip), 'XLSX'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.template'   => [%w(dotx), %w(application/zip), 'DOTX'],
    'application/x-tar'                                                         => [%w(tar), %w(), 'TAR'],
    'application/x-ruby'                                                        => [%w(rb), %w(), 'Ruby'],
    'application/vnd.oasis.opendocument.text'                                   => [%w(odt), %w(application/zip), 'ODT'],
    'application/msword'                                                        => [%w(doc msg rtf dot), %w(), 'DOC'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'   => [%w(docx), %w(application/zip), 'DOCX'],
    'message/rfc822'                                                            => [%w(eml emlx mbx msg), %w(), 'EML'],
    'text-calendar'                                                             => [%w(ical ics), %w(), 'ICAL'],
    'application/vnd.sun.xml.writer'                                            => [%w(sxw), %w(application/zip), 'SXW'],
    'application/vnd.wordperfect'                                               => [%w(wpd), %w(), 'WPD'],
    'video/mpeg'                                                                => [%w(m1a m1v m2a mpeg mpg), %w(), 'MPEG'],
    'video/x-m4v'                                                               => [%w(m4v), %w(), 'M4V'],
    'video/quicktime'                                                           => [%w(mov qt), %w(), 'Quicktime'],
    'audio/mpeg'                                                                => [%w(mp1 mp2 mp3), %w(), 'MPEG Audio'],
    'audio/mp3'                                                                 => [%w(mp3), %w(), 'MP3'],
    'video/realmedia'                                                           => [%w(rm), %w(), 'Realmedia'],
    'video/x-matroska'                                                          => [%w(webm mkv), %w(), 'Webmedia'],
    'video/x-ms-wmv'                                                            => [%w(wmv), %w(), 'Windows Media Video'],
    'video/mp4'                                                                 => [%w(mp4), %w(), 'MP4'],
    'video/avi'                                                                 => [%w(avi), %w(), 'AVI'],
    'application/pdf'                                                           => [%w(pdf), %w(), 'PDF'],
    'application/x-rtf'                                                         => [%w(rtf), %w(), 'RTF'],
    'application/rtf'                                                           => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/rtf'                                                                  => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/richtext'                                                             => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'application/doc'                                                           => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'application/x-soffice'                                                     => [%w(rtf), %w(application/x-rtf), 'RTF'],
    'text/x-java'                                                               => [%w(java), %w(text/plain), "Java"],
    'text/java'                                                                 => [%w(java), %w(text/plain), "Java"],
    'text/x-java-source'                                                        => [%w(java), %w(text/plain), "Java"],
    'application/ms-java'                                                       => [%w(java), %w(text/plain), "Java"],
    'application/x-7z-compressed'                                               => [%w(7z), %w(), "7zip"],
    'application/vnd.rar'                                                       => [%w(rar), %w(), "Rar"],
    'application/vnd.ms-outlook'                                                => [%w(pab pst ost), %w(), 'PST'],
  }
  # @private
  # :nodoc:
  MAGIC = [
    ['application/zip',                             [[0, "\x50\x4B\x03\x04"]]],
    ['application/msword',                          [[0, "\xEC\xA5\xC1\x00"]]],
    ['application/excel',                           [[0, "\x09\x08\x10\x00\x00\x06\x05\x00"]]],
    ['application/mspowerpoint',                    [[0, "\xFD\xFF\xFF\xFF", [5, "\x00\x00\x00"]]]],
    ['application/rtf',                             [[0, "\x7B\x5C\x72\x74\x66\x31"]]],
    ['application/pdf',                             [[0, "\x25\x50\x44\x46"]]],
    ['text/xml',                                    [[0, "\x72\x73\x69\x6F\x6E\x3D\x22\x31\x2E\x30\x22\x3F\x3E"]]],
    ['text/plain',                                  [[0, "\xEF\xBB\xBF"]]],
    ['text/plain',                                  [[0, "\xFE\xFF"]]],
    ['text/plain',                                  [[0, "\xFF\xFE"]]],
    ['text/plain',                                  [[0, "\x00\x00\xFE\xFF"]]],
    ['text/plain',                                  [[0, "\xFF\xFE\x00\x00"]]],
    ['image/jpeg',                                  [[0, "\xFF\xD8\xFF"]]],
    ['image/png',                                   [[0, "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A"]]],
    ['image/gif',                                   [[0, "\x47\x49\x46\x38", [5, "\x61"]]]],
    ['image/bmp',                                   [[0, "\x66\x77"]]],
    ['image/x-icon',                                [[0, "\x00\x00\x01\x00"]]],
    ['application/gzip',                            [[0, "\x1F\x8B\x08"]]],
    ['application/x-7z-compressed',                 [[0, "\x66\x77"]]],
    ['application/x-7z-compressed',                 [[0, "\x37\x7A\xBC\xAF\x27\x1C"]]],
    ['application/vnd.rar',                         [[0, "\x52\x61\x72\x21"]]],
    ['application/octet-stream',                    [[0, "\x4D\x5A"]]],
    ['application/x-tar',                           [[0, "\x1F\x9D"]]],
    ['application/x-tar',                           [[0, "\x1F\xA0"]]],
    ['application/x-tar',                           [[257, "\x75\x73\x74\x61\x72\x00\x30\x30"]]],
    ['application/x-tar',                           [[257, "\x75\x73\x74\x61\x72\x20\x20\x00"]]],
    ['application/x-bzip',                          [[0, "\x42\x5A\x68"]]],
    ['application/ogg',                             [[0, "\x67\x67\x83\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00"]]],
    ['audio/midi',                                  [[0, "\x4D\x54\x68\x64"]]],
    ['audio/wav',                                   [[0, "\x52\x49\x46\x46", [8, "\x57\x41\x56\x45\x66\x6D\x74\x20"]]]],
    ['application/vnd.ms-outlook',                  [[0, "\x21\x42\x44\x4E"]]],
    ['application/acad',                            [[0, "\x41\x43\x31\x30"]]],
    ['application/x-photoshop',                     [[0, "\x38\x42\x50\x53"]]],
    ['message/rfc822',                              [[0, "\x46\x72\x6F\x6D"]]],
    ['text/plain',                                  [[0, ""]]],
  ]
end

#word
